version: '3.7'

services:
  node:
    container_name: node-design-patterns
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    # command: sh -c "npm install && npm run dev"